return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={ ArrowsignEnable=false, HungerCost=1, Ownership=false, SanityCost=1 },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1898292532"]={
    configuration_options={
      antlion=true,
      atrium_gate=false,
      bearger=true,
      beequeenhive=false,
      crabking=false,
      deerclops=true,
      dragonfly=false,
      hound=true,
      klaus_sack=false,
      malbatross=false,
      prime_mate=true,
      tips_method=1,
      toadstool=false 
    },
    enabled=true 
  },
  ["workshop-2208128427"]={
    configuration_options={
      LOOT_PUMP_EQUIP=true,
      LOOT_PUMP_SCALE=1,
      LOOT_PUMP_SOUND=true,
      LOOT_PUMP_SPEED=1,
      LOOT_PUMP_TWOZN=false,
      LOOT_PUMP_WALLS=true 
    },
    enabled=true 
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="Auto",
      show_buddle_item=1,
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-2505341606"]={
    configuration_options={
      ANNOUNCE_MODE=true,
      CLEANDAYS=10,
      axe=3,
      bee=20,
      beefalo=50,
      birdtrap=10,
      blueprint=3,
      bugnet=3,
      burntground=5,
      clean=true,
      compass=3,
      cutgrass=50,
      deer=10,
      driftwood_log=130,
      earmuffshat=3,
      evergreen_sparse=150,
      feather=2,
      festival=2,
      firehound=1,
      fishingrod=3,
      flies=8,
      flint=50,
      frog=20,
      glommerfuel=10,
      guano=1,
      hammer=3,
      heatrock=10,
      hound=15,
      houndstooth=2,
      lang=true,
      log=50,
      manrabbit_tail=20,
      marsh_tree=100,
      mosquitosack=10,
      nitre=50,
      oceanfishingrod=3,
      pickaxe=3,
      pinecone=50,
      pitchfork=3,
      pocket_scale=3,
      poop=5,
      razor=3,
      rock_petrified_tree=150,
      rocks=50,
      rocky=20,
      rottenegg=2,
      seeds=3,
      shovel=3,
      silk=10,
      skeleton_player=20,
      sketch=1,
      slurtle=10,
      slurtleslime=2,
      spear=3,
      spider=15,
      spiderden=40,
      spidergland=10,
      spoiled_fish=2,
      spoiled_food=2,
      stack=true,
      stack_fireflies=true,
      stack_scanning_range=10,
      stinger=2,
      tacklesketch=1,
      test_mode=false,
      torch=3,
      trap=30,
      twiggytree=150,
      twigs=50,
      winterhat=3 
    },
    enabled=true 
  },
  ["workshop-2798599672"]={
    configuration_options={
      config_render=true,
      slot_amulet="extrabody3",
      slot_armor="extrabody1",
      slot_clothing="extrabody2" 
    },
    enabled=true 
  },
  ["workshop-2839945490"]={
    configuration_options={
      can_light_grass=false,
      can_light_sapling=false,
      danger_announce=true,
      droppos="moonbase",
      hit_beefalo="none",
      lighttime=10,
      onstart_resource=true,
      show_bundle_owner=true,
      show_ui=true,
      showtitle="yes",
      visitortime=15 
    },
    enabled=true 
  },
  ["workshop-356930882"]={
    configuration_options={ uses=10000000, uses2=10000000, uses3=10000000 },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=3,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=5,
      MOD_RESTART_CD_RESURRECT=7,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=2,
      MOD_RESTART_RESURRECT_HEALTH=0,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=6 
    },
    enabled=true 
  },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-599498678"]={ configuration_options={  }, enabled=true },
  ["workshop-659304077"]={
    configuration_options={
      jgbattackrange=3,
      jgbcanuseashammer=false,
      jgbcanuseasshovel=false,
      jgbdamage=100,
      jgbfiniteuses=0,
      jgblightintensity=0.6,
      jgblightradius=1,
      jgbmovespeedmul=1.2 
    },
    enabled=true 
  },
  ["workshop-728459184"]={
    configuration_options={
      INCREASEBACKPACKSIZES_BACKPACK=10,
      INCREASEBACKPACKSIZES_ICEPACK=10,
      INCREASEBACKPACKSIZES_KRAMPUSSACK=16,
      INCREASEBACKPACKSIZES_PIGGYBACK=14,
      largerbundlecontainer=4,
      largerchester=12,
      largerdragonflychest=16,
      largericebox=24,
      largertreasurechest=12 
    },
    enabled=true 
  } 
}