name = "Beefalo Widget"
version = "1.7"
local russian = language == "ru"
description = russian and "версия: "..version or "version: "..version
author = "charlie"
api_version = 10
forumthread = ""
icon_atlas = "modicon.xml"
icon = "modicon.tex"
dst_compatible = true
client_only_mod = false
all_clients_require_mod = true
server_filter_tags = {"beefalo widget v" .. version}
priority = -1.9999999990
configuration_options = 
{
	{
		name = "horizontal",
        label = russian and "позиция по горизонтали" or "horizontal position",
        options =
        {
            {description = "-1320", data = -1320},
            {description = "-1290", data = -1290},
            {description = "-1260", data = -1260},
            {description = "-1230", data = -1230},
            {description = "-1200", data = -1200},
            {description = "-1170", data = -1170},
            {description = "-1140", data = -1140},
            {description = "-1110", data = -1110},
            {description = "-1080", data = -1080},
            {description = "-1050", data = -1050},
            {description = "-1020", data = -1020},
            {description = "-990", data = -990},
            {description = "-960", data = -960},
            {description = "-930", data = -930},
            {description = "-900", data = -900},
            {description = "-870", data = -870},
            {description = "-840", data = -840},
            {description = "-810", data = -810},
            {description = "-780", data = -780},
            {description = "-750", data = -750},
            {description = "-720", data = -720},
            {description = "-690", data = -690},
            {description = "-660", data = -660},
            {description = "-630", data = -630},
            {description = "-600", data = -600},
            {description = "-570", data = -570},
            {description = "-540", data = -540},
            {description = "-510", data = -510},
            {description = "-480", data = -480},
            {description = "-450", data = -450},
            {description = "-420", data = -420},
            {description = "-390", data = -390},
            {description = "-360", data = -360},
            {description = "-330", data = -330},
            {description = "-300", data = -300},
            {description = "-270", data = -270},
            {description = "-240", data = -240},
            {description = "-210", data = -210},
            {description = "-180", data = -180},
            {description = "-150", data = -150},
            {description = "-120", data = -120},
            {description = "-90", data = -90},
            {description = "-60", data = -60},
            {description = "-30", data = -30},
            {description = russian and "0 (центр)" or "0 (center)", hover = russian and "по умолчанию" or "by default", data = 0},
            {description = "30", data = 30},
            {description = "60", data = 60},
            {description = "90", data = 90},
            {description = "120", data = 120},
            {description = "150", data = 150},
            {description = "180", data = 180},
            {description = "210", data = 210},
            {description = "240", data = 240},
            {description = "270", data = 270},
            {description = "300", data = 300},
            {description = "330", data = 330},
            {description = "360", data = 360},
            {description = "390", data = 390},
            {description = "420", data = 420},
            {description = "450", data = 450},
            {description = "480", data = 480},
            {description = "510", data = 510},
            {description = "540", data = 540},
            {description = "570", data = 570},
            {description = "600", data = 600},
            {description = "630", data = 630},
            {description = "660", data = 660},
            {description = "690", data = 690},
            {description = "710", hover = russian and "оптимально для 5 слотов экипировки" or "optimal for 5 equip slots", data = 710},
            {description = "720", data = 720},
            {description = "750", data = 750},
            {description = "780", data = 780},
            {description = "810", data = 810},
            {description = "840", data = 840},
            {description = "870", data = 870},
            {description = "900", data = 900},
            {description = "930", data = 930},
            {description = "960", data = 960},
            {description = "990", data = 990},
            {description = "1020", data = 1020},
            {description = "1050", data = 1050},
            {description = "1080", data = 1080},
            {description = "1110", data = 1110},
            {description = "1140", data = 1140},
            {description = "1170", data = 1170},
            {description = "1200", data = 1200},
            {description = "1230", data = 1230},
            {description = "1260", data = 1260},
            {description = "1290", data = 1290},
            {description = "1320", data = 1320},
        },
        default = 0,
	},
	{
		name = "vertical",
		hover = russian and "влево - опустить, вправо - поднять" or "left - down, right - up",
        label = russian and "позиция по вертикали" or "vertical position",
        options =
        {
            {description = "-120", data = -120},
            {description = "-115", data = -115},
            {description = "-110", data = -110},
            {description = "-105", data = -105},
            {description = "-100", data = -100},
            {description = "-95", data = -95},
            {description = "-90", data = -90},
            {description = "-85", data = -85},
            {description = "-80", data = -80},
            {description = "-75", data = -75},
            {description = "-70", data = -70},
            {description = "-65", data = -65},
            {description = "-60", data = -60},
            {description = "-55", data = -55},
            {description = "-50", data = -50},
            {description = "-45", data = -45},
            {description = "-40", data = -40},
            {description = "-35", data = -35},
            {description = "-30", hover = russian and "по умолчанию" or "by default", data = -30},
            {description = "-25", data = -25},
            {description = "-20", data = -20},
            {description = "-15", data = -15},
            {description = "-10", data = -10},
            {description = "-5", data = -5},
            {description = "0", data = 0},
            {description = "5", data = 5},
            {description = "10", data = 10},
            {description = "15", data = 15},
            {description = "20", data = 20},
            {description = "25", data = 25},
            {description = "30", data = 30},
            {description = "35", data = 35},
            {description = "40", data = 40},
            {description = "45", data = 45},
            {description = "50", data = 50},
            {description = "55", data = 55},
            {description = "60", data = 60},
        },
        default = -30,
	},
	{
		name = "info",
		hover = russian and "показывает информацию при наведении мыши на бифа" or "shows information when you hover the mouse",
        label = russian and "показать информацию" or "show info",
        options =
        {
			{description = russian and "нет" or "no", data = false},
            {description = russian and "да" or "yes", data = true},
        },
        default = false,
	},	
}	